### ISSUE TITLE
remove aria-wg-active.md and aria-wg-participants.md ?

### ISSUE THREAD

**Issue by spectranaut** [w3c/aria-common#109]
Maybe follow up to @pkra's work here: https://github.com/w3c/aria-common/issues/103

I don't think I understand the purpose of either of these two files:
- [aria-wg-active.md](https://github.com/w3c/aria-common/blob/506138b2135fe7076fbb960b8de93d2503320071/acknowledgements/aria-wg-active.html)
- [aria-wg-participants.md](https://github.com/w3c/aria-common/blob/main/acknowledgements/aria-wg-participants.html)

The "aria working group active" is still pulled into the editors draft, and contains out of date information: https://w3c.github.io/aria/#ack_group

Can we delete these files, and delete this section or auto generate it, or generate it only when publishing?

----

* [x] https://github.com/w3c/aria-common/pull/111
* [ ] ARIA https://github.com/w3c/aria/pull/2117
* [ ] ACCNAME
* [x] HTML-AAM - does not have a WG list
* [ ] CORE-AAM
* [ ] DPUB-AAM  - custom, hardcoded list - maybe update?
* [x] DPUB-ARIA - does not have a WG list
* [ ] SVG-AAM - custom, hardcoded list - maybe update?
* [ ] GRAPHICS-ARIA - custom, hardcoded list - maybe update?
* [ ] GRAPHICS-AAM - custom, hardcoded list - maybe update?
* [ ] MATHML-AAM

**Comment by pkra** [comment]
This was discussed in this week's meeting. @daniel-montalvo will look to see if there's an w3c API we can use to regularly update the active participants list.

**Comment by daniel-montalvo** [comment]
@pkra @spectranaut 

W3C has indeed a new API for this.

w3c/aria#2117 shows how we could do this.

I'd suggest not to automate enabling funders as this will depend on Team efforts and other funded related stuff. Still fairly manual.

**Comment by pkra** [comment]
As I wrote on https://github.com/w3c/aria/pull/2117 I think we can adopt this immediately since the new script is separate from aria.js.

I also noticed that some specs don't have the list of members (e.g., html-aam). I recall that a while back we talked about perhaps only having the full WG list on just the ARIA spec.

In any case, I'll adjust the top card to track the various specs.

**Comment by daniel-montalvo** [comment]
Work is now on W3c/aria-common#111

**Comment by pkra** [comment]
#111 is merged. As per today's meeting, it's time to create the downstream PRs to roll things out.
