### ISSUE TITLE
Path to css/common.css in github.io is 404ing out

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria-common#19]
The ARIA (and other?) specs viewed in github.io point to https://w3c.github.io/aria/common/css/common.css. That file 404s out. As a result, things like the Characteristics Table look less nice.

**Comment by jnurthen** [comment]
There are no 404 errors when viewing 
https://w3c.github.io/accname/
https://w3c.github.io/aria/
https://w3c.github.io/core-aam/
