### ISSUE TITLE
Resolve inconsistent jQuery references

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-common#21]
Respec removed jQuery - they added it back for now. https://github.com/w3c/respec/pull/2027 Eventually we will need to either reference ourselves or remove it - but for now we need to consistently reference it.

There are 2 instances of `jQuery.` rather than `$.`
Propose changing these to `$.` to get us unbroken

**Comment by michael-n-cooper** [comment]
Fixed by a82822fe62069e00dcd5cfc0057193f2bfac7d42
