### ISSUE TITLE
TypeError: "$.fn.details is undefined" encountered in mapping-tables.js

### ISSUE THREAD

**Issue by joanmarie** [w3c/aria-common#27]
If you load Core-AAM, you now get the following ReSpec error:

    TypeError: "$.fn.details is undefined"

mapping-tables.js is using the jquery-details plugin. This used to work (or at least didn't use to give us an error). A quick git bisect of respec indicates this issue was introduced in v24.0.0.

Update: The specific commit is https://github.com/w3c/respec/commit/d5a62ba5. At least it's appropriately named ("BREAKING CHANGE: migrate to webpack"). :grinning:

**Comment by joanmarie** [comment]
@marcoscaceres: If you have a spare moment and a hint about what we should update in response to the webpack migration change it would be super. Thank you in advance!

**Comment by jnurthen** [comment]
jQuery-details is expecting jQuery to be jQuery not $
Adding a  line in core-aam of
```<script>
	jQuery = $;
</script>
```
will resolve it but it would be easier if respec would do this :)

**Comment by marcoscaceres** [comment]
ReSpec fix incoming. Sorry about this!

**Comment by marcoscaceres** [comment]
Just pushed this fix https://github.com/w3c/respec/pull/2027 in respec@24.2.1. 

Let me know if that addresses the issue.

**Comment by joanmarie** [comment]
> Just pushed this fix [w3c/respec#2027](https://github.com/w3c/respec/pull/2027) in respec@24.2.1.
> 
> Let me know if that addresses the issue.

Seems to. Thanks for the super-quick fix, @marcoscaceres!!
