### ISSUE TITLE
ARIA specs are borked

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-common#29]
For example all the role tables are not rendered correctly
https://w3c.github.io/aria/#role_definitions

**Comment by carmacleod** [comment]
None of the `<rref>`s are generating links, either.

**Comment by jnurthen** [comment]
Logged https://github.com/w3c/respec/issues/2147

**Comment by jnurthen** [comment]
Until respec issue is resolved have fixed the aria spec with https://github.com/w3c/aria/commit/add3cd125a882b512604f3b875560db09b12e239 (also in master)
