### ISSUE TITLE
out of date links for accessibility APIs

### ISSUE THREAD

**Issue by scottaohara** [w3c/aria-common#34]
I found that the [macOS Accessibility Protocol link](https://developer.apple.com/documentation/appkit/accessibility/nsaccessibility) goes to a page stating:
>A legacy, informal protocol that is not recommended for active use.

Additionally in the Important Terms section the link [Linux/Unix Accessibility Toolkit](https://developer.gnome.org/atk/unstable/) returns a 403.

@cookiecrook and @joanmarie can you verify where the preferred urls these links should point to now?  I can make the PR / will also update HTML AAM accordingly.

Thanks

**Comment by cookiecrook** [comment]
This is probably the best link for the Mac reference.
https://developer.apple.com/library/archive/documentation/Accessibility/Conceptual/AccessibilityMacOSX/index.html

Optionally, you could leave the link text the same and reference:
https://developer.apple.com/documentation/appkit/nsaccessibility

**Comment by scottaohara** [comment]
thank you
