### ISSUE TITLE
Improve automation

### ISSUE THREAD

**Issue by carmacleod** [w3c/aria-common#37]
For background, please follow this circular thread that occurred after https://github.com/w3c/aria/pull/1165 was merged:
- https://github.com/w3c/aria/issues/1160#issuecomment-605644873
- https://github.com/w3c/aria/issues/1160#issuecomment-605646802
- all of https://github.com/w3c/aria/pull/1227
- over to here https://github.com/w3c/aria-common/pull/36
- back to https://github.com/w3c/aria/issues/1160#issuecomment-606237009

Can we create some kind of bot account for making those automatic commits, so that there's a hint where to look when things go wrong?

Also, if there's conflicts, maybe the copy can fail and ping somebody? It was just a fluke that I happened to look at the live region definition and notice the Ajax back in there AND it was recent enough that I remembered making the change... I wonder if other changes have been overwritten at some point and nobody noticed.

**Comment by jnurthen** [comment]
To be honest that is my job and I failed here. I normally will notice if a PR includes changes to aria-common and resolve the issues at that point.
It may be a better use of time to add automation to fail (or at least add a warning) to a PR if it changes anything in aria-common.

**Comment by carmacleod** [comment]
That makes sense - catch it at the source. Good idea.

**Comment by carmacleod** [comment]
Shall I open an issue in the aria repo to automate making sure a PR does not have any changes in `aria/common` and close this issue?

**Comment by carmacleod** [comment]
Opened https://github.com/w3c/aria/issues/1228.
