### ISSUE TITLE
Set up automatic syncing with spec repos

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/aria-common#5]
(And maybe update the README in the meantime to make it clear that it's not set up yet?)

In the meantime, good old copy-paste between folders on my local machine seems to do the trick (https://github.com/w3c/svg-aam/commit/b827b9eab02ed917cfe9fc7bdc600fa0cbbbc5d3), but if there's a better solution, that could go in the README, too.

**Comment by michael-n-cooper** [comment]
Fixed via https://github.com/w3c/aria-common/commit/0977149ebee7e54fe7b776e8e7eff3d610bf1407

**Comment by AmeliaBR** [comment]
So if any other repos wanted to auto-sync, the editors should submit a PR adding a new line here?

https://github.com/w3c/aria-common/blob/0977149ebee7e54fe7b776e8e7eff3d610bf1407/.travis.yml#L17-L18
