### ISSUE TITLE
Expand / Collapse all Role mappings

### ISSUE THREAD

**Issue by clapierre** [w3c/aria-common#73]
In section : 7.2 Role Mapping Table

If you do the following single expansion of items no longer displays the "details" for the roles.

1. Click Expand All.
2. Click Collapse All.
3. Try to expand any role 

Result: Nothing happens item's information does not show in any browser tested (Safari, FF, Chrome)
Expected: Single role's details to show like happens prior to expanding / collapse all.

**Comment by jnurthen** [comment]
@schne324 can you take a look to see what is happening here?

**Comment by schne324** [comment]
> @schne324 can you take a look to see what is happening here?

Sure, I will take a look

**Comment by jnurthen** [comment]
It is the Expand All / Collapse All buttons in the role and state and properties section in the AAMs. 
## Core-aam
* https://w3c.github.io/core-aam/#mapping_role_table
* https://w3c.github.io/core-aam/#mapping_state-property_table
## Dpub-aam
* https://w3c.github.io/dpub-aam/#mapping_role_table
## HTML-aam
* https://w3c.github.io/html-aam/#html-element-role-mappings
* https://w3c.github.io/html-aam/#html-attribute-state-and-property-mappings
